package tk.zwander.oneuituner.util.values.integers

import android.content.Context
import tk.zwander.oneuituner.util.prefs
import tk.zwander.overlaylib.ResourceData
import tk.zwander.overlaylib.ResourceFileData
import tk.zwander.overlaylib.makeResourceXml

fun Context.makeDefault11Integers(): ResourceFileData {
    return ResourceFileData(
            "integers",
            "values",
            makeResourceXml(
                    ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns",
                            prefs.headerCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_fold",
                            prefs.headerCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_tablet",
                            prefs.headerCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_fold_sub",
                            prefs.headerCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows",
                            prefs.qsRowCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_tablet",
                            prefs.qsRowCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_fold",
                            prefs.qsRowCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_fold_sub",
                            prefs.qsRowCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "quick_settings_num_columns",
                            prefs.qsColCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns",
                            prefs.qsColCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_tablet",
                            prefs.qsColCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_power_saving",
                            prefs.qsColCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_fold",
                            prefs.qsColCountPortrait.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_fold_sub",
                            prefs.qsColCountPortrait.toString()
                    )
            )
    )
}

fun Context.makeLandscape11Integers(): ResourceFileData {
    return ResourceFileData(
            "integers",
            "values",
            makeResourceXml(
                    ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns",
                            prefs.headerCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_fold",
                            prefs.headerCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_tablet",
                            prefs.headerCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_fold_sub",
                            prefs.headerCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows",
                            prefs.qsRowCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_tablet",
                            prefs.qsRowCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_fold",
                            prefs.qsRowCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_fold_sub",
                            prefs.qsRowCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "quick_settings_num_columns",
                            prefs.qsColCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns",
                            prefs.qsColCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_tablet",
                            prefs.qsColCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_power_saving",
                            prefs.qsColCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_fold",
                            prefs.qsColCountLandscape.toString()
                    ),
                    ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_fold_sub",
                            prefs.qsColCountLandscape.toString()
                    )
            )
    )
}