package tk.zwander.oneuituner.util.values.integers

import android.content.Context
import tk.zwander.oneuituner.util.prefs
import tk.zwander.overlaylib.ResourceData
import tk.zwander.overlaylib.ResourceFileData
import tk.zwander.overlaylib.makeResourceXml

fun Context.makeDefault11Integers(): ResourceFileData {
    return ResourceFileData(
        "integers",
        "values",
        makeResourceXml(
            arrayListOf<ResourceData>().apply {
                if (prefs.adjustQsHeader) {
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns",
                            prefs.headerCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_fold",
                            prefs.headerCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_tablet",
                            prefs.headerCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_fold_sub",
                            prefs.headerCountPortrait.toString()
                        )
                    )
                }
                if (prefs.adjustQsGrid) {
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows",
                            prefs.qsRowCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_tablet",
                            prefs.qsRowCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_fold",
                            prefs.qsRowCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_fold_sub",
                            prefs.qsRowCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "quick_settings_num_columns",
                            prefs.qsColCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns",
                            prefs.qsColCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_tablet",
                            prefs.qsColCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_power_saving",
                            prefs.qsColCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_fold",
                            prefs.qsColCountPortrait.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_fold_sub",
                            prefs.qsColCountPortrait.toString()
                        )
                    )
                }
            }
        )
    )
}

fun Context.makeLandscape11Integers(): ResourceFileData {
    return ResourceFileData(
        "integers",
        "values",
        makeResourceXml(
            arrayListOf<ResourceData>().apply {
                if (prefs.adjustQsHeader) {
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns",
                            prefs.headerCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_fold",
                            prefs.headerCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_tablet",
                            prefs.headerCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_qs_panel_max_columns_fold_sub",
                            prefs.headerCountLandscape.toString()
                        )
                    )
                }

                if (prefs.adjustQsGrid) {
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows",
                            prefs.qsRowCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_tablet",
                            prefs.qsRowCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_fold",
                            prefs.qsRowCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_max_rows_fold_sub",
                            prefs.qsRowCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "quick_settings_num_columns",
                            prefs.qsColCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns",
                            prefs.qsColCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_tablet",
                            prefs.qsColCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_power_saving",
                            prefs.qsColCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_fold",
                            prefs.qsColCountLandscape.toString()
                        )
                    )
                    add(
                        ResourceData(
                            "integer",
                            "sec_quick_settings_num_columns_fold_sub",
                            prefs.qsColCountLandscape.toString()
                        )
                    )
                }
            }
        )
    )
}